[package]
name = "bread-baguette"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
owo-code = "0.1.1"
uwuify = "0.2.2"
